steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/endless-fire-432406-d8/my-app:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/endless-fire-432406-d8/my-app:latest']

  # Step 3: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl set image deployment/my-app my-app=gcr.io/endless-fire-432406-d8/my-app
        kubectl rollout status deployment/my-app

# Optionally specify the timeout (in seconds)
timeout: 1200s

# Substitutions for the build
substitutions:
  _APP_NAME: 'my-app'
  _REGION: 'us-central1'
  _CLUSTER_NAME: 'my-cluster'

# Options to specify the options for Cloud Build
options:
  logging: 'CLOUD_LOGGING_ONLY'
